### ISSUE TITLE
Namefake is down

### ISSUE THREAD

**Issue by git-akihakune** [git-akihakune/aWaifu#1]
![index](https://user-images.githubusercontent.com/87116762/144200638-33594d5c-f350-4e36-a2e9-fab2ace293a3.gif)

## I. Error message
```python
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.namefake.com', port=443): Max retries exceeded with url: /random/female (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5234e26970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

## II. Reproduce
Details in the gif above.

## III. Fix
- Wait for Namefake to solve their issues
- Use a Python module to replace the need of Namefake

## Full traceback
```python
Traceback (most recent call last):
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5234e26970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.namefake.com', port=443): Max retries exceeded with url: /random/female (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5234e26970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/aWaifu-0.1.2-py3.9.egg/aWaifu/__main__.py", line 8, in <module>
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/aWaifu-0.1.2-py3.9.egg/aWaifu/__main__.py", line 5, in main
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/aWaifu-0.1.2-py3.9.egg/aWaifu/utils.py", line 177, in generateProfiles
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/aWaifu-0.1.2-py3.9.egg/aWaifu/utils.py", line 124, in _getRandomProfile
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/aki/Programming/module/awaifu-test/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.namefake.com', port=443): Max retries exceeded with url: /random/female (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5234e26970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by git-akihakune** [comment]
https://user-images.githubusercontent.com/87116762/145666509-2ec61573-491b-47e8-94e0-e014d457972a.mp4

Namefake is up and running. No-namefake implementation is currently being under development.
